navbar:
  blog_title: Blog

# 首页
index:
  # 页面顶部大图
  banner_img: /img/banner/index.jpg

  slogan:
    enable: true
    text: 这是一条 Slogan
    api:
      enable: true
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

# 文章页
post:
  banner_img: https://www.dmoe.cc/random.php

# 归档页
archive:
  banner_img: /img/banner/lake.webp

# 分类页
category:
  banner_img: /img/banner/mountain.webp

# 标签页
tag:
  banner_img: /img/banner/tag.webp

# 关于页
about:
  name: "kiah"
  intro: "这是一个用来记录学习与成长的个人博客"
  banner_img: /img/banner/about.webp
  icons:
    - {
        class: "iconfont icon-github-fill",
        link: "https://github.com/hazelnutXD",
        tip: "GitHub",
      }
    - {
        class: "iconfont icon-bilibili-fill",
        link: "https://space.bilibili.com/4215402",
        tip: "bilibili",
      }
